name: NerfFarms
version: '${project.version}'
main: simplexity.nerffarms.NerfFarms
api-version: "1.20"
author: Rhythmic, Peashooter101
website: https://github.com/Simplexity-Development/NerfFarms
description: Allows greater control over farming on your server